spring:
  # config: jdbc-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 666666

    # config: hikari
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1


# config: mybatis
mybatis:
  type-aliases-package: com.github.ybqdren.pojo
  mapper-locations: class:mapper/*.xml