# choice env
spring:
  profiles:
    active: dev

# config: server port
server:
  port: 8906
  tomcat:
    uri-encoding: utf-8

# config: log
logging:
  level:
    com.github.ybqdren.isendserver: debug

