spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_jpa
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: 123